### ISSUE TITLE
[Bug]: Unable to view or edit mask on Image on In-painting mode. 

### ISSUE THREAD

**Issue by syddharth** [anapnoe/stable-diffusion-webui-ux#79] opened 2023-04-24 13:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When uploading an image of Inpainting tab, I can't see the image.

Before Upload:
![image](https://user-images.githubusercontent.com/15185829/234003663-97cae179-4783-40cb-be60-15d8b223d7ec.png)

After Uploading an image to inpaint tab:
![image](https://user-images.githubusercontent.com/15185829/234003821-873a57d5-cfd8-4350-884e-8bc98894f7ec.png)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

I should have been able to use the inpaint feature like normal. Also, the image should have been visible. 

### Commit where the problem happens

4589dbeaff435f20165ce661304198fa2c230e99

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --force-enable-xformers --api --listen --allow-code --enable-insecure-extension-access --opt-channelslast --disable-safe-unpickle
```

### List of extensions

![image](https://user-images.githubusercontent.com/15185829/234004271-c2714543-3630-4542-b465-eb2ec901c5d8.png)

### Console logs

```Shell
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.8s (load scripts: 0.6s, list SD models: 1.1s, create ui: 7.0s, gradio launch: 3.0s).
```

**Comment by anapnoe** [comment] 2023-04-24 13:15
can you disable non inbuild extensions and see if the issue persists ?

**Comment by anapnoe** [comment] 2023-04-25 02:56
cant reproduce close the issue

**Closed by anapnoe** 2023-04-25 02:56 UTC
