### ISSUE TITLE
[Bug]: Extension Reload/Restart causes hangs

### ISSUE THREAD

**Issue by robonxt** [anapnoe/stable-diffusion-webui-ux#176] opened 2023-06-21 09:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I toggle a extension's state (enabled to disabled) and press the reload button to save changes, the console gives me this error:

```C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit```

And it never continues the restart process. I've noticed that it only happens during extension restarts.

To kill it, I have to open Task Manager to force quit python, otherwise I cannot even control+c out of the program.

This issue seem to happen only after I set my extensions folder as a hard junction link to a folder (as I experiment with multiple UI systems).

### Steps to reproduce the problem

1. Go to Extensions tab
2. Install any extension / toggle state of a user-installed extension
3. Reload/Restart using the restart button 
4. Hang forever?

### What should have happened?

It should reload and restart the WebUI with no issues, with the new extensions being updated to reflect changes.

### Version or Commit where the problem happens

v1.4.0 (directml backend mod)

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows, Android

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### Cross attention optimization

V1

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--backend directml 
--enable-insecure-extension-access 
--medvram 
--no-gradio-queue 
--always-batch-cond-uncond 
--no-half 
--precision full 
--upcast-sampling 
--use-cpu CLIP BLIP interrogate gfpgan bsrgan esrgan scunet codeformer 
--opt-split-attention 
--sub-quad-q-chunk-size 512 
--sub-quad-kv-chunk-size 512 
--sub-quad-chunk-threshold 80 
--listen --port 7860 
--skip-torch-cuda-test
```

### List of extensions

OneButtonPrompt
Stable-Diffusion-Webui-Civitai-Helper
a1111-sd-webui-tagcomplete
model_preset_manager
novelai-2-local-prompt
sd-webui-ar
sd-webui-controlnet
stable-diffusion-webui-images-browser
ultimate-upscale-for-automatic1111
webui-qrcode-generator

### Console logs

```Shell
(venv) PS D:\AI\systems\sd-webUX-dml> .\webui-user.bat
venv "D:\AI\systems\sd-webUX-dml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: ## 1.4.0
Commit hash: b64bec88365f5a170c1b941d4ec2b7bae6f80cf5
Installing requirements


Launching Web UI with arguments: --backend directml --enable-insecure-extension-access --medvram --no-gradio-queue --always-batch-cond-uncond --no-half --precision full --upcast-sampling --use-cpu CLIP BLIP interrogate gfpgan bsrgan esrgan scunet codeformer --opt-split-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --listen --port 7860 --skip-torch-cuda-test
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\AI\systems\sd-webUX-dml\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
2023-06-21 01:36:11,898 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: D:\AI\systems\SD-shared\extensions\sd-webui-controlnet\annotator\downloads
2023-06-21 01:36:11,992 - ControlNet - INFO - ControlNet v1.1.224
Loading weights [d4c1719023] from D:\AI\systems\sd-webUX-dml\models\Stable-diffusion\animekawa_v10.safetensors
Creating model from config: D:\AI\systems\sd-webUX-dml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: V1... done.
Textual inversion embeddings loaded(9): 7dirtywords, bad-hands-5, bad-image-v2-39000, badhandv4, easynegative, negative_hand-neg, ng_deepnegative_v1_75t, verybadimagenegative_v1.3, was-gunpla
Model loaded in 1.9s (load weights from disk: 0.5s, create model: 0.4s, apply weights to model: 0.4s, calculate empty prompt: 0.5s).
Server queues disabled
preload_extensions_git_metadata for 21 extensions took 1.26s
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.2s (import torch: 1.3s, import gradio: 1.0s, import ldm: 0.5s, other imports: 0.8s, load scripts: 1.7s, create ui: 2.6s, gradio launch: 4.1s).
Traceback (most recent call last):
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\systems\sd-webUX-dml\modules\ui_extra_networks.py", line 369, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\AI\systems\sd-webUX-dml\modules\ui_extra_networks.py", line 369, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\AI\systems\sd-webUX-dml\modules\ui_extra_networks.py", line 126, in create_html
    for item in self.list_items():
  File "D:\AI\systems\sd-webUX-dml\extensions-builtin\Lora\ui_extra_networks_lora.py", line 16, in list_items
    for index, (name, lora_on_disk) in enumerate(lora.available_loras.items()):
RuntimeError: dictionary changed size during iteration
Restarting UI...
Closing server running on port: 7860
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\AI\systems\sd-webUX-dml\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
2023-06-21 01:37:50,901 - ControlNet - INFO - ControlNet v1.1.224
Server queues disabled
preload_extensions_git_metadata for 21 extensions took 1.05s
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 5.4s (load scripts: 0.4s, create ui: 0.8s, gradio launch: 4.1s).
Loading D:\AI\systems\sd-webUX-dml\models\Stable-diffusion\bluemix_v25a.ckpt...
Converting model...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1819/1819 [00:00<00:00, 1778424.00it/s]
fixed broken clip
[41]
Saving to D:\AI\systems\sd-webUX-dml\models\Stable-diffusion\bluemix_v25a-fp32-no-ema.safetensors...
Loading D:\AI\systems\sd-webUX-dml\models\Stable-diffusion\cuteyukimixSpecializedAnd_kawaShow.ckpt...
Converting model...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1131/1131 [00:00<00:00, 2059816.68it/s]
clip in this model is fine, skip fixing...
Saving to D:\AI\systems\sd-webUX-dml\models\Stable-diffusion\cuteyukimixSpecializedAnd_kawaShow-fp32-no-ema.safetensors...
Restarting UI...
Closing server running on port: 7860
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\AI\systems\sd-webUX-dml\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
2023-06-21 01:41:07,324 - ControlNet - INFO - ControlNet v1.1.224
Server queues disabled
preload_extensions_git_metadata for 21 extensions took 1.06s
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 5.3s (load scripts: 0.4s, create ui: 0.7s, gradio launch: 4.1s).
Traceback (most recent call last):
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\systems\sd-webUX-dml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\systems\sd-webUX-dml\modules\ui_extra_networks.py", line 369, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\AI\systems\sd-webUX-dml\modules\ui_extra_networks.py", line 369, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\AI\systems\sd-webUX-dml\modules\ui_extra_networks.py", line 126, in create_html
    for item in self.list_items():
  File "D:\AI\systems\sd-webUX-dml\extensions-builtin\Lora\ui_extra_networks_lora.py", line 16, in list_items
    for index, (name, lora_on_disk) in enumerate(lora.available_loras.items()):
RuntimeError: dictionary changed size during iteration
C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit
```

### Additional information

The AMD directml backend mod shouldn't affect it, as it only adds the features to use dml instead of cpu and for WebUI to know that a gpu exists

**Comment by evakenshin** [comment] 2023-07-05 05:51
me too

**Comment by robonxt** [comment] 2023-07-05 06:17
I think I found a solution to this, however it might be a issue with the upstream setup. I'll comment in the near future about the steps to fix it (at least how I did it with the directml fork)

**Comment by VelvetAcidChrist** [comment] 2023-07-08 20:39
A simple solution to fix this error:

`pip install --upgrade --force-reinstall pyarrow==11.0.0`

**Comment by robonxt** [comment] 2023-07-08 22:32
> A simple solution to fix this error:
> 
> `pip install --upgrade --force-reinstall pyarrow==11.0.0`

I'll give this a try too. My solution was to rewrite part of the code to reuse the built-in restart function, as according to my python expert sibling,  calling `os._exit()` doesn't exit cleanly and is a big reason why pyarrow is throwing errors.

**Comment by VelvetAcidChrist** [comment] 2023-07-09 01:11
> > A simple solution to fix this error:
> > `pip install --upgrade --force-reinstall pyarrow==11.0.0`
> 
> I'll give this a try too. My solution was to rewrite part of the code to reuse the built-in restart function, as according to my python expert sibling, calling `os._exit()` doesn't exit cleanly and is a big reason why pyarrow is throwing errors.

What's interesting, in pyarrow 11 this is not a serious cause of the error :)
I think this should be fixed, because the problem is not obvious and it's not good of pyarrow developers to break thousands of projects with new versions, some of which already have no support.

**Comment by robonxt** [comment] 2023-07-09 01:18
I am unable to reinstall pyarrow v11 due it forcing numpy to be reinstalled with a different version (some other package needed a specific version of numpy to work). 
However since my fork has already fixed this (supposelly, no issues yet), this might need to be brought up in the main AUTOMATIC1111 repo, unless that was fixed upstream

**Comment by anapnoe** [comment] 2023-11-01 01:03
it has been fixed yes

**Closed by anapnoe** 2023-11-01 01:03 UTC
